project:
  type: website
  output-dir: docs

website:
  title: "Dalanda Jalloh - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
<<<<<<< HEAD
      - text: Labs
        menu:
          - href: labs/lab_0/
            text: "Lab 0: dplyr Basics" 

=======
        text: Labs
        menu:
        - href: labs/lab_0/
          text: "Lab 0: dplyr Basics"
>>>>>>> 6f66688b7db68a6789902b2ecce30699db38dd03

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
